package de.wstein.flixplugin;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

/**
 * How a flixw project's pin is read.
 *
 * <p>
 * The lock below is a real one, copied verbatim from a project pinned to
 * {@code flix/flix 0.75.2}, and the jar name it derives is the real file name
 * in that machine's
 * cache. Both were checked against the wrapper's own vendored source rather
 * than inferred from its
 * output: {@code flixw.java:449} for the cache root, {@code :622} for
 * {@code canonical},
 * {@code :631} for the jar name, {@code :1307} for the JDK marker.
 *
 * <p>
 * An earlier revision of this suite asserted against {@code ./flixw info}'s
 * printed report and
 * described its fixtures as "the actual output". They were not — the digest had
 * been shortened to
 * sixteen characters, so the jar name every test agreed on was one that never
 * exists on disk.
 */
public class FlixwProjectTest {

    /** The digest of the pinned 0.75.2 jar, at the full width flixw writes. */
    private static final String DIGEST = "a2697d875725a0dde6e793b8d54cb220e86167a6d49ec5f0ccb0832966c8c15a";

    private static final String LOCK = """
            # Generated by ./flixw pin. Do not edit by hand; commit this file.
            wrapperVersion = "0.20.0"

            [compiler]
            repo    = "flix/flix"
            version = "0.75.2"
            url     = "https://github.com/flix/flix/releases/download/v0.75.2/flix.jar"
            sha256  = "%s"
            """.formatted(DIGEST);

    @Rule
    public TemporaryFolder folder = new TemporaryFolder();

    /**
     * Distinguishes the projects a single test builds, since a name may only be
     * claimed once.
     */
    private int projects;

    /**
     * A project with a wrapper, a lock, and a cache of its own.
     *
     * <p>
     * The cache is pointed into the project through {@code .envrc} rather than
     * through the
     * process environment, because that is the one lever a test can pull:
     * {@code FLIX_CACHE_HOME}
     * is read from the project file first, exactly as
     * {@link FlixwProject#cacheHome} documents.
     */
    private Path project(String lock) throws Exception {
        Path root = folder.newFolder("wproj" + projects++).toPath();
        Files.writeString(root.resolve(FlixwProject.WRAPPER_POSIX), "#!/bin/sh\nexit 0\n", StandardCharsets.UTF_8);
        Files.createDirectories(root.resolve(".flixw"));
        Files.writeString(root.resolve(FlixwProject.LOCK), lock, StandardCharsets.UTF_8);
        Files.writeString(root.resolve(FlixEnvrc.ENVRC),
                "export FLIX_CACHE_HOME=\"$PWD/cache\"\n", StandardCharsets.UTF_8);
        return root;
    }

    /**
     * Puts a file where flixw would have left the verified jar for
     * {@code version}/{@code digest}.
     */
    private Path cacheJar(Path root, String version, String digest) throws Exception {
        Path compilers = root.resolve("cache").resolve("compilers");
        Files.createDirectories(compilers);
        Path jar = compilers.resolve("flix-" + version + "-" + digest + ".jar");
        Files.writeString(jar, "not really a jar", StandardCharsets.UTF_8);
        return jar;
    }

    @Test
    public void findsTheJarALockPins() throws Exception {
        Path root = project(LOCK);
        Path expected = cacheJar(root, "0.75.2", DIGEST);

        FlixwProject.Installation installation = FlixwProject.resolve(root);

        assertNotNull(installation);
        assertEquals(expected, installation.jar());
    }

    /**
     * Nothing in this class starts a process.
     *
     * <p>
     * The regression this exists for: resolving used to run {@code ./flixw info},
     * and resolving
     * is reached from the language server's startup — so opening a cloned
     * repository executed a
     * script that repository shipped. The wrapper here writes a file if it is ever
     * run, and the
     * assertion is that the file is not there.
     *
     * <p>
     * Fault-injected: with the subprocess restored, the sentinel appears and this
     * fails.
     */
    @Test
    public void openingAProjectRunsNothing() throws Exception {
        Path root = project(LOCK);
        Path sentinel = root.resolve("executed");
        Files.writeString(root.resolve(FlixwProject.WRAPPER_POSIX),
                "#!/bin/sh\ntouch '" + sentinel + "'\n", StandardCharsets.UTF_8);
        root.resolve(FlixwProject.WRAPPER_POSIX).toFile().setExecutable(true);

        FlixwProject.resolve(root);

        assertFalse("resolving executed the project's wrapper script", Files.exists(sentinel));
    }

    /**
     * A fork pins {@code 0.75.2+fork.wstein.260813.1}; its jar is
     * {@code flix-0.75.2-<digest>.jar}.
     *
     * <p>
     * The build metadata identifies the build and the digest already does that in
     * the file name,
     * so flixw does not repeat it. Getting this wrong names a file that never
     * exists, and the
     * symptom is a project that silently falls back to a loose {@code flix.jar}.
     */
    @Test
    public void dropsBuildMetadataFromTheJarName() throws Exception {
        String forked = LOCK.replace("version = \"0.75.2\"", "version = \"0.75.2+fork.wstein.260813.1\"");
        Path root = project(forked);
        Path expected = cacheJar(root, "0.75.2", DIGEST);

        assertEquals(expected, FlixwProject.resolve(root).jar());
        assertEquals("0.75.2", FlixwProject.canonical("0.75.2+fork.wstein.260813.1"));
        assertEquals("0.75.2", FlixwProject.canonical("0.75.2"));
    }

    /**
     * The digest goes into a file name, so a lock that is not one cannot be trusted
     * with it.
     *
     * <p>
     * A lock is a committed file. Without the check, a hostile one reaches outside
     * the cache by
     * writing a digest full of {@code ../}, and the plugin then launches whatever
     * it lands on.
     */
    @Test
    public void refusesADigestThatIsNotOne() throws Exception {
        Path traversal = project(LOCK.replace(DIGEST, "../../../../../../tmp/evil"));
        assertNull(FlixwProject.resolve(traversal).jar());

        Path tooShort = project(LOCK.replace(DIGEST, "a2697d875725a0dd"));
        assertNull(FlixwProject.resolve(tooShort).jar());

        Path notHex = project(LOCK.replace(DIGEST, "Z".repeat(64)));
        assertNull(FlixwProject.resolve(notHex).jar());
    }

    /** Same reasoning for the version, which is interpolated into the same name. */
    @Test
    public void refusesAVersionThatCouldEscapeTheCache() throws Exception {
        Path root = project(LOCK.replace("version = \"0.75.2\"", "version = \"../../../etc/passwd\""));

        assertNull(FlixwProject.resolve(root).jar());
    }

    /**
     * A cache pruned behind flixw's back leaves a lock naming a jar that is gone.
     *
     * <p>
     * Answering with the path anyway defers the failure to {@code java -jar}, which
     * reports it
     * as a missing file with no mention of the wrapper or the pin.
     */
    @Test
    public void aPrunedCacheReportsNothingPinned() throws Exception {
        Path root = project(LOCK);

        assertNull(FlixwProject.resolve(root).jar());
    }

    /**
     * `flixw install` writes the wrapper; `flixw pin` writes the compiler into the
     * lock.
     */
    @Test
    public void anUnpinnedProjectHasNoCompiler() throws Exception {
        Path root = project("# Generated by ./flixw pin.\nwrapperVersion = \"0.20.0\"\n");

        assertNotNull(FlixwProject.resolve(root));
        assertNull(FlixwProject.resolve(root).jar());
    }

    /** A key outside `[compiler]` is not the compiler's, however it is spelled. */
    @Test
    public void readsOnlyTheCompilerTable() throws Exception {
        Path root = project("""
                [other]
                version = "9.9.9"
                sha256  = "%s"
                """.formatted(DIGEST));

        assertNull(FlixwProject.readLock(root.resolve(FlixwProject.LOCK)));
    }

    /**
     * The marker names something that is about to be executed, so it may only name
     * flixw's own JDK.
     *
     * <p>
     * flixw applies the same rule ({@code flixw.java:1315-1320}) and for the same
     * reason. A
     * marker pointing outside {@code jdks/} is not a record of an install; it is an
     * instruction to
     * run someone else's binary.
     */
    @Test
    public void refusesAJdkMarkerPointingOutsideTheCache() throws Exception {
        Path root = project(LOCK);
        Path cache = root.resolve("cache");
        Files.createDirectories(cache.resolve("jdks"));
        Path elsewhere = folder.newFile("java").toPath();
        Files.writeString(cache.resolve("jdks").resolve("default"), elsewhere + "\n", StandardCharsets.UTF_8);

        assertNull(FlixwProject.installedJdk(cache));
    }

    @Test
    public void findsTheJdkFlixwInstalled() throws Exception {
        Path root = project(LOCK);
        Path cache = root.resolve("cache");
        Path java = cache.resolve("jdks").resolve("temurin-22").resolve("bin").resolve("java");
        Files.createDirectories(java.getParent());
        Files.writeString(java, "", StandardCharsets.UTF_8);
        Files.writeString(cache.resolve("jdks").resolve("default"), java + "\n", StandardCharsets.UTF_8);

        assertEquals(java, FlixwProject.installedJdk(cache));
        assertEquals(java, FlixwProject.resolve(root).java());
    }

    /**
     * An absent marker is the ordinary case: flixw uses a system JDK unless it
     * installed one.
     */
    @Test
    public void noMarkerMeansNoOpinion() throws Exception {
        Path root = project(LOCK);

        assertNull(FlixwProject.resolve(root).java());
    }

    /**
     * A project with no wrapper is not a flixw project, and asking costs nothing.
     */
    @Test
    public void aProjectWithoutAWrapperIsNotOne() throws Exception {
        assertNull(FlixwProject.resolve(null));
        assertNull(FlixwProject.resolve(Path.of("/nonexistent-project-root")));
        assertFalse(FlixwProject.isFlixwProject(folder.newFolder("bare").toPath()));
    }

    /**
     * A wrapper with no lock beside it is a stray script, not an installed wrapper.
     */
    @Test
    public void aWrapperWithoutALockIsNotAnInstall() throws Exception {
        Path root = folder.newFolder("stray").toPath();
        Files.writeString(root.resolve(FlixwProject.WRAPPER_POSIX), "#!/bin/sh\n", StandardCharsets.UTF_8);

        assertFalse(FlixwProject.isFlixwProject(root));
        assertNull(FlixwProject.resolve(root));
    }

    /**
     * An unreadable or absent lock answers "nothing pinned" rather than throwing.
     */
    @Test
    public void aLockThatIsNotOneIsNotAFailure() throws Exception {
        assertNull(FlixwProject.readLock(Path.of("/nonexistent/lock.toml")));
        Path root = project("this is not toml at all\n");
        assertNull(FlixwProject.resolve(root).jar());
    }
}
